uploads = []
outputs = []

[[generated]]
id = "3sSWRbQM6htEkuSTJ4n2K"
uri = "file://artifacts/vulnrap/src/assets/logo.png"
type = "image"
title = "vulnrap synthetic bug logo"

[[generated]]
id = "owvJqMc5twUeVWAA8Rq3Z"
uri = "file://artifacts/vulnrap/src/assets/logo_v1.png"
type = "image"
title = "cyberpunk bug x-beam logo v1"

[[generated]]
id = "u5XcsEPWyyFt9VCwrxFqH"
uri = "file://artifacts/vulnrap/src/assets/logo_v2.png"
type = "image"
title = "cyberpunk bug x-beam logo v2"

[[generated]]
id = "i4oVzwEJ4wRw-ys6F7Zvx"
uri = "file://artifacts/vulnrap/src/assets/logo_v3.png"
type = "image"
title = "cyberpunk bug x-beam logo v3"

[[generated]]
id = "UFFKEEqf8Xv3aVDexZrPP"
uri = "file://artifacts/vulnrap/src/assets/logo_v4.png"
type = "image"
title = "cyberpunk bug x-beam logo v4"
